/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseSort: typeof import('./src/components/BaseSort.vue')['default']
    BubbleSort: typeof import('./src/components/BubbleSort.vue')['default']
    HeapSort: typeof import('./src/components/HeapSort.vue')['default']
    InsertionSort: typeof import('./src/components/InsertionSort.vue')['default']
    MergeSort: typeof import('./src/components/MergeSort.vue')['default']
    QuickSort: typeof import('./src/components/QuickSort.vue')['default']
    Rect: typeof import('./src/components/Rect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionSort: typeof import('./src/components/SelectionSort.vue')['default']
    ShellSort: typeof import('./src/components/ShellSort.vue')['default']
    SortWrapper: typeof import('./src/components/SortWrapper.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
