/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/bubbleSort/': RouteRecordInfo<'/bubbleSort/', '/bubbleSort', Record<never, never>, Record<never, never>>,
    '/heapSort/': RouteRecordInfo<'/heapSort/', '/heapSort', Record<never, never>, Record<never, never>>,
    '/insertionSort/': RouteRecordInfo<'/insertionSort/', '/insertionSort', Record<never, never>, Record<never, never>>,
    '/mergeSort/': RouteRecordInfo<'/mergeSort/', '/mergeSort', Record<never, never>, Record<never, never>>,
    '/quickSort/': RouteRecordInfo<'/quickSort/', '/quickSort', Record<never, never>, Record<never, never>>,
    '/radixSort/': RouteRecordInfo<'/radixSort/', '/radixSort', Record<never, never>, Record<never, never>>,
    '/selectionSort/': RouteRecordInfo<'/selectionSort/', '/selectionSort', Record<never, never>, Record<never, never>>,
    '/shellSort/': RouteRecordInfo<'/shellSort/', '/shellSort', Record<never, never>, Record<never, never>>,
  }
}
